# conda build <DIR_WITH_THIS_FILE> --channel soft-matter --channel conda-forge
package:
  name: bstore
  version: "1.0.0"

source:
  git_rev: v1.0.0rc1
  git_url: https://github.com/kmdouglass/bstore.git

requirements:
  build:
    - python
    - setuptools
    - conda
    - nose
    - numpy
    - scipy
    - matplotlib
    - scikit-learn
    - pandas
    - h5py
    - pytables
    - trackpy
    - nb_conda

  run:
    - python
    - nose
    - numpy
    - scipy
    - matplotlib
    - scikit-learn
    - pytables
    - h5py
    - pandas
    - trackpy 0.3.2
    - tifffile 0.9.0
    - nb_conda

test:
  imports:
    - tables
    - bstore

about:
  home: https://github.com/kmdouglass/bstore.git
  license: BSD3
  license_file: LICENSE.txt