# conda build <DIR_WITH_THIS_FILE> --channel soft-matter --channel kmdouglass
package:
  name: bstore
  version: "1.2.1"

source:
  git_rev: v1.2.1
  git_url: https://github.com/kmdouglass/bstore.git

requirements:
  build:
    - python 3.5.2
    - setuptools
    - conda
    - nose

  run:
    - python 3.5.2
    - nose
    - numpy
    - scipy
    - matplotlib 2.0.1
    - scikit-learn
    - pytables
    - h5py
    - pandas 0.19.2
    - trackpy 0.3.2
    - tifffile 0.10.0
    - nb_conda
    - qt
    - pyqt
    - filelock

test:
  imports:
    - tables
    - bstore
    - bstore.gui
    - bstore.datasetTypes

about:
  home: https://github.com/kmdouglass/bstore.git
  license: BSD3
  license_file: LICENSE.txt